### ISSUE TITLE
Usage example error, App ID validation improvements

### ISSUE THREAD

**Issue by Kla35** [elkhayder/Discord-Oauth2#1]
I just want to report 2 issues :
First one, on `$request = new DiscordOauth2( // ALL data are provided by Discordapp.com
        **"6906082258965796170",** 
        "teqTdVfHST1f7OxzIwEr-mPou0bMTn7U",
        "https://www.mywebsite.com/DiscordOauthHandle.php",
        [
            "identify",
            "email",
            "connections",
            "guilds"
        ]
    );`
In your framework, u check if the app id is a int, but in the example, it's a string. (but it works if u remove the quote)
And the second, it's not `$client = $request->fetchData[$authToken]; // Fetch User data` but `$client = $request->fetchData($authToken); // Fetch User data`
Otherwise, the framework works perfectly, thank u :)

**Comment by elkhayder** [comment]
Well, I would like to appreciate you taking from your time o open this request. 
- I did fix the Example error, thanks for noticing.
- For the app id, I did change it from an Integer validation, to a numeric value validation, and it sound far better.

I'd also wanna thank you for your feedback, it feels good knowing that someone out there is using my code.
